<?php if ($this->_support_reminder): ?>
<script type="text/javascript">
/*<![CDATA[*/
jQuery(function($) {
    w3tc_lightbox_support_us();
});
/*]]>*/
</script>
<?php endif; ?>

<div class="wrap" id="w3tc">
    <?php screen_icon('w3tc-logo'); ?>

	<h2>W3 Total Cache <span>by W3 EDGE <sup>&reg;</sup></span></h2>

	<?php foreach ($this->_errors as $error): ?>
    <div class="error">
    	<p><?php echo $error; ?></p>
    </div>
	<?php endforeach; ?>

	<?php foreach ($this->_notes as $note): ?>
	<div class="updated fade">
		<p><?php echo $note; ?></p>
    </div>
    <?php endforeach; ?>

    <h3 id="w3tc-nav">
    	<label>
        	Viewing: 
            <select>
                <optgroup label="Control Panels:">
                    <option value="w3tc_general"<?php selected($this->_page, 'w3tc_general'); ?>>General Settings</option>
                    <option value="w3tc_pgcache"<?php selected($this->_page, 'w3tc_pgcache'); ?>>Page Cache Settings</option>
                    <option value="w3tc_minify"<?php selected($this->_page, 'w3tc_minify'); ?>>Minify Settings</option>
                    <option value="w3tc_dbcache"<?php selected($this->_page, 'w3tc_dbcache'); ?>>Database Cache Settings</option>
                    <option value="w3tc_objectcache"<?php selected($this->_page, 'w3tc_objectcache'); ?>>Object Cache Settings</option>
                    <option value="w3tc_browsercache"<?php selected($this->_page, 'w3tc_browsercache'); ?>>Browser Cache Settings</option>
                    <option value="w3tc_mobile"<?php selected($this->_page, 'w3tc_mobile'); ?>>User Agent Groups Settings</option>
                    <option value="w3tc_cdn"<?php selected($this->_page, 'w3tc_cdn'); ?>>Content Delivery Network (CDN) Settings&nbsp;</option>
                </optgroup>
                <optgroup label="Help:">
                    <option value="w3tc_faq"<?php selected($this->_page, 'w3tc_faq'); ?>>Frequently Asked Questions</option>
                    <option style="color: red;" value="w3tc_support"<?php selected($this->_page, 'w3tc_support'); ?>>Support</option>
                    <option value="w3tc_install"<?php selected($this->_page, 'w3tc_install'); ?>>Install</option>
                    <option value="w3tc_about"<?php selected($this->_page, 'w3tc_about'); ?>>About</option>
                </optgroup>
            </select>
        </label>
    </h3>
 