<?php if (! $ajax): include W3TC_DIR . '/inc/options/common/header.phtml'; ?>
<p>
    Request professional services, suggest a feature or submit a bug using the form below:
</p>
<?php endif; ?>

<div id="support_container">
    <form action="admin.php?page=<?php echo $this->_page; ?>" method="post" enctype="multipart/form-data" id="support_form">
    	<?php include W3TC_DIR . '/inc/options/support/' . $request_type . '.phtml'; ?>
    
        <fieldset>
        	<legend>Notes</legend>
    
    		<ul>
    			<li>All submitted data will not be saved and is used solely for the purposes your support request. You will not be added to a mailing list, solicited without your permission, nor will your site be administered after this support case is closed.</li>
    			<li>Instead of providing your primary administrative or <acronym title="Secure Shell">SSH</acronym> / <acronym title="File Transfer Protocol">FTP</acronym> accounts, create a new administrator account that can be disabled when the support case is closed.</li>
    			<li>Please add the domain w3-edge.com to your <a href="http://en.wikipedia.org/wiki/Whitelist" target="_blank">email whitelist</a> as soon as possible.</li>
    		</ul>
        </fieldset>
    
        <p>
    		<input type="hidden" name="request_type" value="<?php echo $request_type; ?>" />
    		<input type="hidden" name="payment" value="<?php echo $payment; ?>" />
        	<input type="submit" name="support_request" class="button-primary" value="Submit request" />
    		<input id="support_cancel" type="button" value="Cancel" class="button-primary" />
        </p>
    </form>
</div>

<?php if (! $ajax) include W3TC_DIR . '/inc/options/common/footer.phtml'; ?>
