<?php if (! $ajax): include W3TC_DIR . '/inc/options/common/header.phtml'; ?>
<p>
    Request professional services, suggest a feature or submit a bug using the form below:
</p>
<?php endif; ?>

<div id="support_container">
    <form id="support_select_form" class="w3tc-ignore-change" action="admin.php" method="get">
        <div class="metabox-holder">
        	<?php echo $this->postbox_header('Choose request type'); ?>
            <table class="form-table">
            	<tr>
                    <th><label for="support_request_type">Request type:</label></th>
                    <td>
                        <input type="hidden" name="page" value="<?php echo $this->_page; ?>" /> 
                        <select id="support_request_type" name="request_type">
                            <option value="">-- Choose Type --</option>
                            <?php foreach ($this->_request_groups as $_request_group => $_request_types): ?>
                            <optgroup label="<?php echo htmlspecialchars($_request_group); ?>:">
                            <?php foreach ($_request_types as $_request_type): ?>
                            	<option value="<?php echo $_request_type; ?>"><?php echo htmlspecialchars($this->_request_types[$_request_type]); ?></option>
                            <?php endforeach; ?>
                            </optgroup>
                            <?php endforeach; ?>
                        </select>
                    </td>
            	</tr>
            </table>
        	<?php echo $this->postbox_footer(); ?>
        </div>
    </form>
</div>

<?php if (! $ajax) include W3TC_DIR . '/inc/options/common/footer.phtml'; ?>
